In [1]:
import pandas as pd

In [2]:
import nltk 
import numpy as np

In [3]:
filename = 'spam.csv'
df = pd.read_csv(filename,encoding = 'latin-1')
#df = pd.read_csv(filename,encoding = 'utf-8')
print(df.shape)
print(df.columns)
print(df.head(2))

(5572, 5)
Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')
    v1                                                 v2 Unnamed: 2  \
0  ham  Go until jurong point, crazy.. Available only ...        NaN   
1  ham                      Ok lar... Joking wif u oni...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  


In [4]:
data = df.values
print(data.shape)

(5572, 5)


In [5]:
print(data[:2])

[['ham'
  'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
  nan nan nan]
 ['ham' 'Ok lar... Joking wif u oni...' nan nan nan]]


In [6]:
lines = data[:,1]
labels = data[:,0]
print(lines[:5])
print(labels[:20])

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 'U dun say so early hor... U c already then say...'
 "Nah I don't think he goes to usf, he lives around here though"]
['ham' 'ham' 'spam' 'ham' 'ham' 'spam' 'ham' 'ham' 'spam' 'spam' 'ham'
 'spam' 'spam' 'ham' 'ham' 'spam' 'ham' 'ham' 'ham' 'spam']


In [8]:
# tách từ trong từng câu 
from nltk import ngrams
sentences = [nltk.word_tokenize(sent) for sent in lines]
print(sentences[0])
# thêm 2 gram 


['Go', 'until', 'jurong', 'point', ',', 'crazy', '..', 'Available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet', '...', 'Cine', 'there', 'got', 'amore', 'wat', '...']


In [12]:
for sent in lines:
    words = nltk.word_tokenize(sent)
    gram2=ngrams(words,2)
    join_grams = ['_'.join(list(gram)) for gram in gram2]
    print(join_grams)

['Go_until', 'until_jurong', 'jurong_point', 'point_,', ',_crazy', 'crazy_..', '.._Available', 'Available_only', 'only_in', 'in_bugis', 'bugis_n', 'n_great', 'great_world', 'world_la', 'la_e', 'e_buffet', 'buffet_...', '..._Cine', 'Cine_there', 'there_got', 'got_amore', 'amore_wat', 'wat_...']
['Ok_lar', 'lar_...', '..._Joking', 'Joking_wif', 'wif_u', 'u_oni', 'oni_...']
['Free_entry', 'entry_in', 'in_2', '2_a', 'a_wkly', 'wkly_comp', 'comp_to', 'to_win', 'win_FA', 'FA_Cup', 'Cup_final', 'final_tkts', 'tkts_21st', '21st_May', 'May_2005', '2005_.', '._Text', 'Text_FA', 'FA_to', 'to_87121', '87121_to', 'to_receive', 'receive_entry', 'entry_question', 'question_(', '(_std', 'std_txt', 'txt_rate', 'rate_)', ')_T', 'T_&', '&_C', "C_'s", "'s_apply", 'apply_08452810075over18', "08452810075over18_'s"]
['U_dun', 'dun_say', 'say_so', 'so_early', 'early_hor', 'hor_...', '..._U', 'U_c', 'c_already', 'already_then', 'then_say', 'say_...']
['Nah_I', 'I_do', "do_n't", "n't_think", 'think_he', 'he_goe

['We_are', 'are_at', 'at_grandmas', 'grandmas_.', '._Oh', 'Oh_dear', 'dear_,', ',_u', 'u_still', 'still_ill', 'ill_?', '?_I', 'I_felt', 'felt_Shit', 'Shit_this', 'this_morning', 'morning_but', 'but_i', 'i_think', 'think_i', 'i_am', 'am_just', 'just_hungover', 'hungover_!', '!_Another', 'Another_night', 'night_then', 'then_.', '._We', 'We_leave', 'leave_on', 'on_sat', 'sat_.']
['Urgent_Ur', 'Ur_å£500', 'å£500_guaranteed', 'guaranteed_award', 'award_is', 'is_still', 'still_unclaimed', 'unclaimed_!', '!_Call', 'Call_09066368327', '09066368327_NOW', 'NOW_closingdate04/09/02', 'closingdate04/09/02_claimcode', 'claimcode_M39M51', 'M39M51_å£1.50pmmorefrommobile2Bremoved-MobyPOBox734LS27YF']
['Nothing_but', 'but_we', 'we_jus', 'jus_tot', 'tot_u', 'u_would', 'would_ask', 'ask_cos', 'cos_u', 'u_ba', 'ba_gua', 'gua_...', '..._But', 'But_we', 'we_went', 'went_mt', 'mt_faber', 'faber_yest', 'yest_...', '..._Yest', 'Yest_jus', 'jus_went', 'went_out', 'out_already', 'already_mah', 'mah_so', 'so_today

['Congratulations_ur', 'ur_awarded', 'awarded_either', 'either_å£500', 'å£500_of', 'of_CD', 'CD_gift', 'gift_vouchers', 'vouchers_&', '&_Free', 'Free_entry', 'entry_2', '2_our', 'our_å£100', 'å£100_weekly', 'weekly_draw', 'draw_txt', 'txt_MUSIC', 'MUSIC_to', 'to_87066', '87066_TnCs', 'TnCs_www.Ldew.com', 'www.Ldew.com_1', '1_win150ppmx3age16']
['Lol_great', 'great_now', 'now_im', 'im_getting', 'getting_hungry', 'hungry_.']
['Yes_..', '.._now', 'now_only', 'only_saw', 'saw_your', 'your_message', 'message_..']
["I_'ll", "'ll_be", 'be_at', 'at_mu', 'mu_in', 'in_like', 'like_&', '&_lt', 'lt_;', ';_#', '#_&', '&_gt', 'gt_;', ';_seconds']
['Ok_...']
['THING_R', 'R_GOOD', 'GOOD_THANX', 'THANX_GOT', 'GOT_EXAMS', 'EXAMS_IN', 'IN_MARCH', 'MARCH_IVE', 'IVE_DONE', 'DONE_NO', 'NO_REVISION', 'REVISION_?', '?_IS', 'IS_FRAN', 'FRAN_STILL', 'STILL_WITH', 'WITH_BOYF', 'BOYF_?', '?_IVE', 'IVE_GOT', 'GOT_TA', 'TA_INTERVIW', 'INTERVIW_4', '4_EXETER', 'EXETER_BIT', 'BIT_WORRIED', 'WORRIED_!', '!_x']
['Tell_

['Sad_story', 'story_of', 'of_a', 'a_Man', 'Man_-', '-_Last', 'Last_week', 'week_was', 'was_my', "my_b'day", "b'day_.", '._My', 'My_Wife', "Wife_did'nt", "did'nt_wish", 'wish_me', 'me_.', '._My', 'My_Parents', 'Parents_forgot', 'forgot_n', 'n_so', 'so_did', 'did_my', 'my_Kids', 'Kids_.', '._I', 'I_went', 'went_to', 'to_work', 'work_.', '._Even', 'Even_my', 'my_Colleagues', 'Colleagues_did', 'did_not', 'not_wish', 'wish_.', '._As', 'As_I', 'I_entered', 'entered_my', 'my_cabin', 'cabin_my', 'my_PA', 'PA_said', 'said_,', ',_``', '``_Happy', "Happy_B'day", "B'day_Boss", 'Boss_!', '!_!', "!_''", "''_.", '._I', 'I_felt', 'felt_special', 'special_.', '._She', 'She_askd', 'askd_me', 'me_4', '4_lunch', 'lunch_.', '._After', 'After_lunch', 'lunch_she', 'she_invited', 'invited_me', 'me_to', 'to_her', 'her_apartment', 'apartment_.', '._We', 'We_went', 'went_there', 'there_.', '._She', 'She_said', 'said_,', ",_''", "''_do", 'do_u', 'u_mind', 'mind_if', 'if_I', 'I_go', 'go_into', 'into_the', 'the_be

['I_dont', 'dont_thnk', 'thnk_its', 'its_a', 'a_wrong', 'wrong_calling', 'calling_between', 'between_us']
['I_am', 'am_not', 'not_sure', 'sure_about', 'about_night', 'night_menu', 'menu_.', '._.', '._.', '._I', 'I_know', 'know_only', 'only_about', 'about_noon', 'noon_menu']
['ARR_birthday', 'birthday_today', 'today_:', ':_)', ')_i', 'i_wish', 'wish_him', 'him_to', 'to_get', 'get_more', 'more_oscar', 'oscar_.']
['Say_this', 'this_slowly.', 'slowly._?', '?_GOD', 'GOD_,', ',_I', 'I_LOVE', 'LOVE_YOU', 'YOU_&', '&_amp', 'amp_;', ';_I', 'I_NEED', 'NEED_YOU', 'YOU_,', ',_CLEAN', 'CLEAN_MY', 'MY_HEART', 'HEART_WITH', 'WITH_YOUR', 'YOUR_BLOOD.Send', 'BLOOD.Send_this', 'this_to', 'to_Ten', 'Ten_special', 'special_people', 'people_&', '&_amp', 'amp_;', ';_u', 'u_c', 'c_miracle', 'miracle_tomorrow', 'tomorrow_,', ',_do', 'do_it', 'it_,', ',_pls', 'pls_,', ',_pls', 'pls_do', 'do_it', 'it_...']
['Open_rebtel', 'rebtel_with', 'with_firefox', 'firefox_.', '._When', 'When_it', 'it_loads', 'loads_just',

['Bloomberg_-Message', '-Message_center', 'center_+447797706009', '+447797706009_Why', 'Why_wait', 'wait_?', '?_Apply', 'Apply_for', 'for_your', 'your_future', 'future_http', 'http_:', ':_//careers', '//careers_.', '._bloomberg.com']
['i_am', 'am_seeking', 'seeking_a', 'a_lady', 'lady_in', 'in_the', 'the_street', 'street_and', 'and_a', 'a_freak', 'freak_in', 'in_the', 'the_sheets', 'sheets_.', '._Is', 'Is_that', 'that_you', 'you_?']
['My_phone']
['Haha_figures', 'figures_,', ',_well', 'well_I', 'I_found', 'found_the', 'the_piece', 'piece_and', 'and_priscilla', "priscilla_'s", "'s_bowl"]
['Actually_fuck', 'fuck_that', 'that_,', ',_just', 'just_do', 'do_whatever', 'whatever_,', ',_do', 'do_find', 'find_an', 'an_excuse', 'excuse_to', 'to_be', 'be_in', 'in_tampa', 'tampa_at', 'at_some', 'some_point', 'point_before', 'before_january', 'january_though']
['URGENT_!', '!_We', 'We_are', 'are_trying', 'trying_to', 'to_contact', 'contact_U.', 'U._Todays', 'Todays_draw', 'draw_shows', 'shows_that'

['In_The', 'The_Simpsons', 'Simpsons_Movie', 'Movie_released', 'released_in', 'in_July', 'July_2007', '2007_name', 'name_the', 'the_band', 'band_that', 'that_died', 'died_at', 'at_the', 'the_start', 'start_of', 'of_the', 'the_film', 'film_?', '?_A-Green', 'A-Green_Day', 'Day_,', ',_B-Blue', 'B-Blue_Day', 'Day_,', ',_C-Red', 'C-Red_Day', 'Day_.', '._(', '(_Send', 'Send_A', 'A_,', ',_B', 'B_or', 'or_C', 'C_)']
["That_'s", "'s_a", 'a_shame', 'shame_!', '!_Maybe', 'Maybe_cld', 'cld_meet', 'meet_for', 'for_few', 'few_hrs', 'hrs_tomo', 'tomo_?']
['Lol_I', 'I_would', 'would_but', 'but_despite', 'despite_these', 'these_cramps', 'cramps_I', 'I_like', 'like_being', 'being_a', 'a_girl', 'girl_.']
['I_canåÕt', 'canåÕt_wait', 'wait_for', 'for_cornwall', 'cornwall_.', '._Hope', 'Hope_tonight', 'tonight_isnåÕt', 'isnåÕt_too', 'too_bad', 'bad_as', 'as_well', 'well_but', 'but_itåÕs', 'itåÕs_rock', 'rock_night', 'night_shite', 'shite_.', '._Anyway', 'Anyway_iåÕm', 'iåÕm_going', 'going_for', 'for_a', 'a_

['Thanks_4', '4_your', 'your_continued', 'continued_support', 'support_Your', 'Your_question', 'question_this', 'this_week', 'week_will', 'will_enter', 'enter_u', 'u_in2', 'in2_our', 'our_draw', 'draw_4', '4_å£100', 'å£100_cash', 'cash_.', '._Name', 'Name_the', 'the_NEW', 'NEW_US', 'US_President', 'President_?', '?_txt', 'txt_ans', 'ans_to', 'to_80082']
["I_'m", "'m_home", 'home_.', '._Doc', 'Doc_gave', 'gave_me', 'me_pain', 'pain_meds', 'meds_says', 'says_everything', 'everything_is', 'is_fine', 'fine_.']
["It_'s", "'s_Ì©", 'Ì©_only', 'only_$', '$_140', '140_ard', 'ard_...', '..._Ìä', 'Ìä_rest', 'rest_all', 'all_ard', 'ard_$', '$_180', '180_at', 'at_least', 'least_...', '..._Which', 'Which_is', 'is_Ì©', 'Ì©_price', 'price_4', '4_Ì©', 'Ì©_2', '2_bedrm', 'bedrm_(', '(_$', '$_900', '900_)']
['Me_too', 'too_!', '!_Have', 'Have_a', 'a_lovely', 'lovely_night', 'night_xxx']
['Prepare_to', 'to_be', 'be_pleasured', 'pleasured_:', ':_)']
['Hi_.', '._:', ':_)', ')_technical', 'technical_support.

['So_how', 'how_are', 'are_you', 'you_really', 'really_.', '._What', 'What_are', 'are_you', 'you_up', 'up_to', 'to_.', '._How', "How_'s", "'s_the", 'the_masters', 'masters_.', '._And', 'And_so', 'so_on', 'on_.']
["I_'m", "'m_at", 'at_bruce', 'bruce_&', '&_amp', 'amp_;', ';_fowler', 'fowler_now', 'now_but', 'but_I', "I_'m", "'m_in", 'in_my', 'my_mom', "mom_'s", "'s_car", 'car_so', 'so_I', 'I_ca', "ca_n't", "n't_park", 'park_(', '(_long', 'long_story', 'story_)']
['I_dont', 'dont_know', 'know_oh', 'oh_.', '._Hopefully', 'Hopefully_this', 'this_month', 'month_.']
['Hi_elaine', 'elaine_,', ',_is', 'is_today', "today_'s", "'s_meeting", 'meeting_confirmed', 'confirmed_?']
['Ok_k', 'k_..', '.._sry', 'sry_i', 'i_knw', 'knw_2', '2_siva', 'siva_..', '.._tats', 'tats_y', 'y_i', 'i_askd', 'askd_..']
['Sorry_,', ',_I', "I_'ll", "'ll_call", 'call_later']
['U_horrible', 'horrible_gal', 'gal_...', '..._U', 'U_knew', 'knew_dat', 'dat_i', 'i_was', 'was_going', 'going_out', 'out_wif', 'wif_him', 'him_yes

In [8]:
from keras.preprocessing.text import Tokenizer 
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
# kiểm tra từ điểm tạo trong tokenizer
#print(tokenizer.word_index)

In [9]:
#texts_to_matrix(tokenizer, texts, mode = c("binary", "count", "tfidf", "freq"))
X = tokenizer.texts_to_matrix(sentences,mode='binary')
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 1. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]]


In [10]:
# chia tập train và tập test 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=0)

In [11]:
from sklearn.linear_model import LogisticRegression  
model_LR = LogisticRegression()
model_LR = model_LR.fit(X_train,y_train)
y_pred = model_LR.predict(X_test)

In [12]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       949
        spam       0.99      0.89      0.93       166

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [13]:
from sklearn.naive_bayes import MultinomialNB   
model_NB = MultinomialNB()
model_NB = model_NB.fit(X_train,y_train)
y_pred = model_NB.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.99      0.99      0.99       949
        spam       0.93      0.92      0.92       166

    accuracy                           0.98      1115
   macro avg       0.96      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [17]:
input_sen = 'I don\'t think he goes to usf, he lives around here throught'
tokens = nltk.word_tokenize(input_sen)

In [18]:
X_input = tokenizer.texts_to_matrix([tokens],mode='binary')
print(X_input)

[[0. 0. 1. ... 0. 0. 0.]]


In [19]:
y_pred = model_NB.predict(X_input)
print(y_pred)

['ham']


In [23]:
from nltk.corpus import stopwords
stopwords.words("english")[100:110]

['here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each']